name: humanoidcursor
description: Your project description.
version: 1.0.0

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter
  camera:  ^0.10.5+9
  google_ml_kit: ^0.16.3
  http: any
  material_color_utilities: ^0.11.1
  meta: ^1.11.0
  permission_handler: ^11.3.1
  dotenv: ^4.2.0